[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sentiocp_cli_demo"
version = "0.1.0"
description = "A command-line demo showcasing SentioCP AI capabilities with OpenAI-powered question answering."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "MIT" }
authors = [
  { name = "[sentiocp]", email = "[team@sentiocp.ai]" }
]
dependencies = [
  "openai>=1.0.0"
]
